#!/bin/bash
require git cargo
is_cargo_project || return 0

# don't repopulate on prepare-commit-msg
git_hook_matches prepare-commit-msg && return 0

## In a rust/cargo project, when a $LAST_TEST_DIR is present then hardlink the /target
## build artifacts to the current test dir this can speed up builds.
if [[ "${LAST_TEST_DIR:-}" ]]; then
    debug "populating from $LAST_TEST_DIR/target"
    [[ -d "$LAST_TEST_DIR/target" ]] && cp -rluf "$LAST_TEST_DIR/target" "./"
fi

