#!/bin/bash
# shellcheck disable=SC2046
## checks with 'cargo audit'
require git cargo

git_branch_matches "master" "main" "release.*" "devel" || return 0
is_cargo_project || return 0
cargo_tool_installed audit || return 0

git_hook_matches "pre-commit" "pre-merge-commit" "commit-msg" || return 0
git_hook_matches "pre-commit" "pre-merge-commit" && background_schedule && return 0
git_hook_matches "commit-msg" && background_wait && return $(background_result)

run_test cargo audit --color never -D warnings --stale --quiet
