#!/bin/bash
# shellcheck disable=SC2046
## check with 'cargo outdated' that all dependencies are up to date
## runs in background
require git cargo
git_branch_matches "master" "main" "release.*" || return 0
is_cargo_project || return 0
cargo_tool_installed outdated || return 0

git_hook_matches "pre-commit" "pre-merge-commit" "commit-msg" || return 0
git_hook_matches "pre-commit" "pre-merge-commit" && background_schedule && return 0
git_hook_matches "commit-msg" && background_wait && return $(background_result)

# TODO: customize --features
# NOTE: intentionally not --offline --locked --frozen here
run_test cargo outdated --color never --exit-code 1
