#!/bin/bash
# shellcheck disable=SC2046
## check with 'cargo outdated' that all dependencies are up to date
## runs in background
require git cargo
git_branch_matches "master" "main" "release.*" || return 0
is_cargo_project || return 0
# cargo doc has no --version, we use --help instead
cargo_tool_installed doc --help || return 0

git_hook_matches "pre-commit" "pre-merge-commit" "commit-msg" || return 0
git_hook_matches "pre-commit" "pre-merge-commit" && background_schedule && return 0
git_hook_matches "commit-msg" && background_wait && return $(background_result)

export RUSTDOCFLAGS="-D rustdoc::broken_intra_doc_links"
run_test cargo doc --offline
