#!/bin/bash
## shellcheck

require git

## * shellcheck_installed - check if shellcheck is installed
function shellcheck_installed
{
    if command -v shellcheck >/dev/null; then
        debug "shellcheck is installed"
        return 0
    else
        note "shellcheck is not installed"
        return 1
    fi
}

## * shellcheck_is_shscript - check if a file is a shell script
function shellcheck_is_shscript {
    [[ -f "$1" ]] && { head -1 "$1" | grep -q "^#!.*sh" ; }
}

## * shellcheck_list_shscripts - list all shell scripts in the repository
function shellcheck_list_shscripts
{
    for file in $(git ls-files); do
        if shellcheck_is_shscript "$file"; then
            echo "$file"
        fi
    done
}

## * shellcheck_lint - lint all shell scripts in the repository
function shellcheck_lint
{
    # shellcheck disable=SC2046
    shellcheck $(shellcheck_list_shscripts)
}

